# NOTE: All indented lines are indented with a tab character.

CC=gcc
CFLAGS=
DFLAGS=
PROGS= setBits showBits

all: $(PROGS)

%: %.c
        $(CC) $(CFLAGS) $(DFLAGS) $< -o $@

clean:
        rm -f $(PROGS) *.o ~*